[tasks.run]
command = "cargo"
args = ["run", "--features", "dev"]


[tasks.release]
command = "cargo"
args = ["run", "--release"]


[tasks.build]
command = "cargo"
args = ["build", "--release"]


[tasks.distribute]
command = "cargo"
args = ["build", "--release"]
